/* autogenerated by Processing revision 1276 on 2021-11-01 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_40Hz_Flash_Milli extends PApplet {

int time = millis();

 public void setup() {
  /* size commented out by preprocessor */;
  background(0);
  noStroke();
}

 public void draw() {
  background(0);

  fill(255); // sets fill color to white

  int passedMillis = millis() - time; // calculates passed milliseconds
  if(passedMillis >= 25){
      time = millis();
      fill(0,0,0);  // if more than 215 milliseconds passed set fill color to red
  }
  rect(0,0,1280,720); // draw first circle


  fill(255); // fill white
}


  public void settings() { size(1280, 720); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_40Hz_Flash_Milli" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
