/* autogenerated by Processing revision 1276 on 2021-11-01 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_40Hz_Flash_Sketch extends PApplet {

int c1 = color(0,0,0), c2 = color(255,255,255), current;
 public void setup() { 
  frameRate(40);
  /* size commented out by preprocessor */;
  current = c1;
}
 public void draw() { background(current);
if(current==c1) { current = c2; } else { current = c1; }
}


  public void settings() { size(1280, 960); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_40Hz_Flash_Sketch" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
